#!/bin/bash

############################################################
# PRESET                                                   #
############################################################
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

cd "$(dirname "$0")"

############################################################
# CHECK ADMIN PRIVILEGES                                   #
############################################################
if [[ $EUID -ne 0 ]]; then
	echo -e "${RED}This script must be run as root${NC}"
	exit 1
fi

############################################################
# BUILD APPLICATION                                        #
############################################################
qmake rtcs.pro
if [ ! $? == 0 ]; then
	echo -e "${RED}Qmake failed${NC}"
	exit
fi
make
if [ ! $? == 0 ]; then
	echo -e "${RED}Make failed${NC}"
	exit
fi

############################################################
# CREATE FOLDERS                                           #
############################################################
mkdir -p /opt/rtcs
mkdir -p /etc/rtcs
touch /etc/rtcs/rtcs.conf
chmod 666 /etc/rtcs/rtcs.conf

############################################################
# INSTALL APPLICATION                                      #
############################################################
cp bin/rtcs /opt/rtcs


